version: '3.9'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always


  activeMq:
    image: apache/activemq-artemis:latest
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      ACTIVEMQ_USER: artemis
      ACTIVEMQ_PASSWORD: artemis
      ACTIVEMQ_ADMIN_LOGIN: artemis
      ACTIVEMQ_ADMIN_PASSWORD: artemis

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"


volumes:
  mysql_data:
    driver: local
