version: '3.9'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_spring-cloud-network
    restart: always


  activeMq:
    image: apache/activemq-artemis:latest
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      ACTIVEMQ_USER: artemis
      ACTIVEMQ_PASSWORD: artemis
      ACTIVEMQ_ADMIN_LOGIN: artemis
      ACTIVEMQ_ADMIN_PASSWORD: artemis

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - my_spring-cloud-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    restart: no
    depends_on:
      - zookeeper
    ports:
      -  9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER: INTERNAL://kafka:29092,EXTERNAL://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    networks:
      - my_spring-cloud-network

  #kafdrop for Kafka UI
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    restart: no
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKER_CONNECT: kafka:9092
    depends_on:
      - kafka
    networks:
      - my_spring-cloud-network

networks:
  my_spring-cloud-network:

volumes:
  mysql_data: